marketplace/app_shop/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('about/', AboutView.as_view(), name='about'),
    path('catalog/<category>/', ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product'),
    path('product/history/', ProductHistoryListView.as_view(), name='product_history'),
    path('sale/', SaleView.as_view(), name='sale'),
]

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('user/', include('app_users.urls')),
    path('order/', include('app_orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/app_orders/models.py
from django.db import models
from django.urls import reverse

from app_users.models import CustomUser
from app_shop.models import Product


class Delivery(models.Model):
    """ Модель доставки """
    type = models.CharField(max_length=100, verbose_name='название')
    price = models.PositiveIntegerField(verbose_name='цена')
    min_order_cost = models.PositiveIntegerField(default=0, verbose_name='мин. стоимость заказа')

    class Meta:
        db_table = 'delivery'
        verbose_name = 'доставка'
        verbose_name_plural = 'доставки'

    def __str__(self):
        return self.type


class Order(models.Model):
    """ Модель заказа """
    PAYMENT_CHOICES = [('card', 'Онлайн картой'), ('account', 'Онлайн со случайного чужого счёта')]
    STATUS_CHOICES = [('wait', 'Ваша оплата проверяется'), ('paid', 'Оплачен'), ('not_paid', 'Не оплачен')]
    ERROR_CHOICES = [(1, 'Оплата не выполнена, на вашем счёте недостаточно средств'),
                     (2, 'Оплата не выполнена, произошёл сбой при списании средств'),
                     (3, 'Оплата не выполнена, проверьте корректность данных карты'),
                     (4, 'Оплата не выполнена, т.к. вы подозреваетесь в нетолерантности'),
                     (5, 'Что-то пошло не так. Попробуйте в другой раз.')]

    user = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, verbose_name='пользователь')
    city = models.CharField(max_length=150, verbose_name='город')
    address = models.CharField(max_length=500, verbose_name='адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    cost = models.PositiveIntegerField(default=0, verbose_name='стоимость')
    delivery = models.ForeignKey(Delivery, on_delete=models.DO_NOTHING, default=1, verbose_name='способ доставки')
    payment = models.CharField(choices=PAYMENT_CHOICES, max_length=20, default='card', verbose_name='способ оплаты')
    payment_error = models.PositiveSmallIntegerField(choices=ERROR_CHOICES, default=0, verbose_name='ошибка заказа')
    status = models.CharField(choices=STATUS_CHOICES, max_length=20, default='not_paid', verbose_name='статус оплаты')
    comment = models.TextField(max_length=5000, verbose_name='комментарий', blank=True)

    class Meta:
        db_table = 'orders'
        default_related_name = 'orders'
        ordering = ['-created_at']
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Заказ №{self.id} от {self.created_at}.'

    def get_absolute_url(self):
        return reverse('one_order', args=[self.id])

    def get_delivery_cost(self):
        """ Возвращает стоимость доставки """
        if self.delivery.min_order_cost == 0 or self.cost < self.delivery.min_order_cost:
            return self.delivery.price
        return 0

    def get_total_cost(self):
        """ Возвращает стоимость заказа с доставкой """
        result = self.cost + self.get_delivery_cost()
        return result


class OrderItem(models.Model):
    """ Модель строки заказа """
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='заказ', related_name='items')
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING, verbose_name='товар', related_name='order_items')
    quantity = models.PositiveIntegerField(default=1, verbose_name='количество')

    class Meta:
        db_table = 'order_items'
        verbose_name = 'строка заказа'
        verbose_name_plural = 'строки заказов'

    def __str__(self):
        return f'Строка заказа {self.order.id}'

    def get_price(self):
        """ Возвращает стоимость строки заказа """
        result = self.product.price * self.quantity
        return result

marketplace/app_users/forms.py
import re

from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, SetPasswordForm
from django.core.exceptions import ValidationError

from app_users.models import CustomUser


class LoginForm(AuthenticationForm):
    """ Форма аутентификации пользователя """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-input'
            field.field.widget.attrs['data-validate'] = 'require'


class ProfileForm(forms.ModelForm):
    """ Форма профиля пользователя """
    first_name = forms.CharField(required=True, label='ФИО')
    email = forms.EmailField(
        required=True,
        label='E-mail',
        error_messages={'unique': 'Пользователь с таким e-mail уже существует.'}
    )
    phone_number = forms.CharField(
        required=True,
        label='Телефон',
        error_messages={'max_length': '', 'unique': 'Пользователь с таким номером телефона уже существует.'}
    )
    avatar = forms.ImageField(required=False, label='Аватар')

    class Meta:
        model = CustomUser
        fields = ('first_name', 'email', 'phone_number', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-input'
            if field.field.required:
                field.field.widget.attrs['data-validate'] = 'require'
        self.fields['email'].widget.attrs['placeholder'] = 'send@test.test'
        self.fields['phone_number'].widget.attrs['placeholder'] = '+70000000000'

    def clean_phone_number(self):
        raw_phone_number = self.cleaned_data['phone_number']
        phone_number = re.sub(r'\D', '', raw_phone_number)[1:]
        if not re.fullmatch(r'\d{10}', phone_number):
            raise ValidationError('Номер телефона должен состоять из 10 цифр.')
        return phone_number


class RegisterForm(ProfileForm, UserCreationForm):
    """ Форма регистрации пользователя """
    class Meta:
        model = CustomUser
        fields = ('first_name', 'email', 'phone_number', 'password1', 'password2', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Введите пароль повторно'


class PasswordEditForm(SetPasswordForm):
    """ Форма изменения пароля пользователя """
    new_password1 = forms.CharField(
        label='Пароль',
        strip=False,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password',
                                          'placeholder': 'Тут можно изменить пароль',
                                          'class': 'form-input'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label='Подтверждение пароля',
        strip=False,
        required=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password',
                                          'placeholder': 'Введите пароль повторно',
                                          'class': 'form-input'}),
    )

marketplace/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Корзина Megano{% endblock %}

{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Корзина</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'main' %}">Главная</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Корзина</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <form class="form Cart" method="post">{% csrf_token %}
          {% for item in cart %}
          {% with product=item.product %}
          <div class="Cart-product">
            <div class="Cart-block Cart-block_row">
              <div class="Cart-block Cart-block_pict">
                <a class="Cart-pict" href="{{ product.get_absolute_url }}">
                  <img class="Cart-img" src="{{ product.images.first.image.url }}" alt="product image"/>
                </a>
              </div>
              <div class="Cart-block Cart-block_info">
                <a class="Cart-title" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
              </div>
              <div class="Cart-block Cart-block_price">
                <div class="Cart-price">{{ product.price }}&nbsp;₽</div>
              </div>
            </div>
            <div class="Cart-block Cart-block_row">
              <div class="Cart-block Cart-block_amount">
                <div class="Cart-amount">
                  <div class="Amount">
                    <button class="Amount-remove" type="button" onclick="location.href='{% url 'reduce_product' product.id %}'"></button>
                    <input class="Amount-input form-input" name="amount" type="text" value="{{ item.quantity }}"/>
                    <button class="Amount-add" type="button" onclick="location.href='{% url 'add_product' product.id %}'"></button>
                  </div>
                </div>
              </div>
              <div class="Cart-block Cart-block_delete">
                <a class="Cart-delete" href="{% url 'remove_product' product.id %}">
                  <img src="{% static 'assets/img/icons/card/delete.svg' %}" alt="delete.svg"/>
                </a>
              </div>
            </div>
          </div>
          {% endwith %}
          {% empty %}
          <p style="text-align: center">В корзине пока пусто</p>
          {% endfor %}
          <div class="Cart-total">
            <div class="Cart-block Cart-block_total">
              <strong class="Cart-title">Итого:</strong>
              <span class="Cart-price">{{ cart.get_total_price }}&thinsp;₽</span>
            </div>
            <div class="Cart-block">
              <a class="btn btn_success btn_lg" href="{% url 'create_order' %}">Оформить заказ</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

marketplace/templates/orders/one_order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Заказ №{{ order.id }} Megano{% endblock %}

{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Заказ №{{ order.id }}</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'main' %}">Главная</a></li>
            <li class="breadcrumbs-item"><a href="{% url 'order_history' %}">История заказов</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Заказ №{{ order.id }}</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section">
      <div class="wrap">
        <div class="Section-content">
          <div class="Orders"></div>
          <div class="Order">
            <div class="Order-infoBlock">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block">
                    <div class="Order-info Order-info_date">
                      <div class="Order-infoType">Дата заказа:</div>
                      <div class="Order-infoContent">{{ order.created_at|date:"d.m.y" }}</div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">ФИО:</div>
                      <div class="Order-infoContent">{{ user.first_name }}</div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Телефон:</div>
                      <div class="Order-infoContent">{{ user.phone_number }}</div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">E-mail:</div>
                      <div class="Order-infoContent">{{ user.email }}</div>
                    </div>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">Тип доставки:</div>
                      <div class="Order-infoContent">{{ order.delivery }}</div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Город:</div>
                      <div class="Order-infoContent">{{ order.city }}</div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Адрес:</div>
                      <div class="Order-infoContent">{{ order.address }}</div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">Оплата:</div>
                      <div class="Order-infoContent">{{ order.get_payment_display }}</div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">Статус:</div>
                      <div class="Order-infoContent">{{ order.get_status_display }}</div>
                    </div>
                    {% if order.payment_error != 0 %}
                    <div class="Order-info Order-info_error">
                      <div class="Order-infoType">Оплата не прошла:</div>
                      <div class="Order-infoContent">{{ order.get_payment_error_display }}</div>
                    </div>
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="Cart Cart_order">
                {% for item in order_items %}
                {% with product=item.product %}
                <div class="Cart-product">
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_pict">
                      <a class="Cart-pict" href="{{ product.get_absolute_url }}">
                        <img class="Cart-img" src="{{ product.images.first.image.url }}" alt="product image"/>
                      </a>
                    </div>
                    <div class="Cart-block Cart-block_info">
                      <a class="Cart-title" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                    </div>
                    <div class="Cart-block Cart-block_price">
                      <div class="Cart-price">{{ product.price }}&nbsp;₽</div>
                    </div>
                  </div>
                  <div class="Cart-block Cart-block_row">
                    <div class="Cart-block Cart-block_amount">{{ item.quantity }}&nbsp;шт.</div>
                  </div>
                </div>
                {% endwith %}
                {% endfor %}
                <div class="Cart-total">
                  <div class="Cart-block Cart-block_total">
                    <strong class="Cart-title">Итого:<span class="Cart-price">{{ order.cost }}&nbsp;₽</span></strong>
                  </div>
                  {% if order.status == 'not_paid' %}
                  <div class="Cart-block">
                    <a class="btn btn_primary btn_lg" href="{% url 'payment' order.id %}">Оплатить</a>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

marketplace/templates/orders/order.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Оформление заказа Megano{% endblock %}

{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">Оформление заказа</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'main' %}">Главная</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>Оформление заказа</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnRight Section_columnWide Order">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Прогресс заполнения</strong>
            </header>
            <div class="Section-columnContent">
              <ul class="menu menu_vt Order-navigate">
                <li class="menu-item_ACTIVE menu-item">
                  <a class="menu-link" href="#step1">Шаг 1. Параметры пользователя</a>
                </li>
                <li class="menu-item">
                  <a class="menu-link" href="#step2">Шаг 2. Способ доставки</a>
                </li>
                <li class="menu-item">
                  <a class="menu-link" href="#step3">Шаг 3. Способ оплаты</a>
                </li>
                <li class="menu-item">
                  <a class="menu-link" href="#step4">Шаг 4. Подтверждение заказа</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <form class="form" method="post">{% csrf_token %}
            <div class="form-error">
              {{ order_form.non_field_errors }}
            </div>
            <div class="Order-block Order-block_OPEN" id="step1">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">Шаг 1. Параметры пользователя</h2>
                <div class="form-error">
                  {{ form.non_field_errors }}
                </div>
              </header>
              <div class="row">
                <div class="row-block">
                  {% for field in form.visible_fields|slice:":3" %}
                  <div class="form-group">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                    <div class="form-error">
                      <ul class="error-list">
                      {% for error in field.errors %}
                        <li>{{ error|escape }}</li>
                      {% endfor %}
                      </ul>
                    </div>
                    {% endif %}
                  </div>
                  {% endfor %}
                </div>
                {% if not request.user.is_authenticated %}
                <div class="row-block">
                  {% for field in form.visible_fields|slice:"3:5" %}
                  <div class="form-group">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                    <div class="form-error">
                      <ul class="error-list">
                      {% for error in field.errors %}
                        <li>{{ error|escape }}</li>
                      {% endfor %}
                      </ul>
                    </div>
                    {% endif %}
                  </div>
                  {% endfor %}
                  <div class="form-group">
                    <a class="btn btn_muted Order-btnReg" href="{% url 'login' %}?next={% url 'order_create' %}">Я уже зарегистрирован</a>
                  </div>
                </div>
                {% endif %}
              </div>
              <div class="Order-footer">
                <a class="btn btn_success Order-next" href="#step2">Дальше</a>
              </div>
            </div>
            <div class="Order-block" id="step2">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">Шаг 2. Способ доставки</h2>
              </header>
              <div class="form-group">
                {% for radio in order_form.delivery %}
                <div>
                  <label class="toggle" for="{{ radio.id_for_label }}">
                    {{ radio.tag }}
                    <span class="toggle-box"></span>
                    <span class="toggle-text">{{ radio.choice_label }}</span>
                  </label>
                </div>
                {% endfor %}
              </div>
              {% for field in order_form.visible_fields|slice:":2" %}
              <div class="form-group">
                <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                <div class="form-error">
                  <ul class="error-list">
                  {% for error in field.errors %}
                    <li>{{ error|escape }}</li>
                  {% endfor %}
                  </ul>
                </div>
                {% endif %}
              </div>
              {% endfor %}
              <div class="Order-footer">
                <a class="btn btn_success Order-next" href="#step3">Дальше</a>
              </div>
            </div>
            <div class="Order-block" id="step3">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">Шаг 3. Способ оплаты</h2>
              </header>
              <div class="form-group">
                {% for radio in order_form.payment %}
                <div>
                  <label class="toggle" for="{{ radio.id_for_label }}">
                    {{ radio.tag }}
                    <span class="toggle-box"></span>
                    <span class="toggle-text">{{ radio.choice_label }}</span>
                  </label>
                </div>
                {% endfor %}
              </div>
              <div class="Order-footer">
                <a class="btn btn_success Order-next" href="#step4">Дальше</a>
              </div>
            </div>
            <div class="Order-block" id="step4">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">Шаг 4. Подтверждение заказа</h2>
              </header>
              <!--+div.Order.-confirmation-->
              <div class="Order-infoBlock">
                <div class="Order-personal">
                  <div class="row">
                    <div class="row-block">
                      <div class="Order-info">
                        <div class="Order-infoType">ФИО:</div>
                        <div class="Order-infoContent js-order-name"></div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">Телефон:</div>
                        <div class="Order-infoContent js-order-phone"></div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">E-mail:</div>
                        <div class="Order-infoContent js-order-email"></div>
                      </div>
                    </div>
                    <div class="row-block">
                      <div class="Order-info Order-info_delivery">
                        <div class="Order-infoType">Тип доставки:</div>
                        <div class="Order-infoContent js-order-delivery"></div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">Город:</div>
                        <div class="Order-infoContent js-order-city"></div>
                      </div>
                      <div class="Order-info">
                        <div class="Order-infoType">Адрес:</div>
                        <div class="Order-infoContent js-order-address"></div>
                      </div>
                      <div class="Order-info Order-info_pay">
                        <div class="Order-infoType">Оплата:</div>
                        <div class="Order-infoContent js-order-payment"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="Cart Cart_order">
                  {% for item in cart %}
                  {% with product=item.product %}
                  <div class="Cart-product">
                    <div class="Cart-block Cart-block_row">
                      <div class="Cart-block Cart-block_pict">
                        <a class="Cart-pict" href="{{ product.get_absolute_url }}">
                          <img class="Cart-img" src="{{ product.images.first.image.url }}" alt="product image"/>
                        </a>
                      </div>
                      <div class="Cart-block Cart-block_info">
                        <a class="Cart-title" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                      </div>
                      <div class="Cart-block Cart-block_price">
                        <div class="Cart-price">{{ item.price }}&nbsp;₽</div>
                      </div>
                    </div>
                    <div class="Cart-block Cart-block_row">
                      <div class="Cart-block Cart-block_amount">{{ item.quantity }}&nbsp;шт.</div>
                    </div>
                  </div>
                  {% endwith %}
                  {% endfor %}
                  <div class="Cart-total">
                    <div class="Cart-block Cart-block_total">
                      <strong class="Cart-title">Итого:</strong>
                      <span class="Cart-price">{{ cart.get_total_price }}&nbsp;₽</span>
                    </div>
                    <div class="Cart-block">
                      <button class="btn btn_primary btn_lg" type="submit">Оплатить</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block js %}
  {{ block.super }}
  <script>
  $(function() {
    $("#id_phone_number").mask("+7 (999) 999-99-99");
  });
  </script>
{% endblock %}

marketplace/templates/orders/order_history.html
{% extends 'base.html' %}
{% load static %}

{% block title %}История заказов Megano{% endblock %}

{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">История заказов</h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="{% url 'main' %}">Главная</a></li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>История заказов</span></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">Навигация</strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'account' %}">Личный кабинет</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'profile' %}">Профиль</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="{% url 'order_history' %}">История заказов</a>
                  </li>
                  <li class="menu-item">
                    <a class="menu-link" href="{% url 'product_history' %}">История просмотра</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Orders">
            {% for order in orders_list %}
            <div class="Order Order_anons">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block">
                    <a class="Order-title" href="{{ order.get_absolute_url }}">
                      Заказ&#32;<span class="Order-numberOrder">№{{ order.id }}</span>
                      &#32;от&#32;<span class="Order-dateOrder">{{ order.created_at|date:"d.m.Y" }}</span>
                    </a>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">Тип доставки:</div>
                      <div class="Order-infoContent">{{ order.delivery }}</div>
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">Оплата:</div>
                      <div class="Order-infoContent">{{ order.get_payment_display }}</div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">Общая стоимость:</div>
                      <div class="Order-infoContent"><span class="Order-price">{{ order.cost }}&nbsp;₽</span></div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">Статус:</div>
                      <div class="Order-infoContent">{{ order.get_status_display }}</div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% empty %}
            <p style="text-align: center">Заказов пока нет</p>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}